In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss, accuracy_score
from statistics import mean
from sklearn.metrics import accuracy_score
import sys
import urllib.request

sys.path.insert(0, "../")
# from model_training.preprocessor_research_paper import preprocess_data
from preprocessor import preprocess_data

In [8]:
NUM_ROWS = 100

In [10]:
df = pd.read_csv("../data/uci_phishing_url_dataset.csv", index_col=False)
# randomise data
df = df.sample(frac=1, ignore_index=True)
df

,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,IsLegit
0,http://www.zakariabek.com,25,www.zakariabek.com,18,0,com,71.836735,1.000000,0.522907,0.058160,...,0,0,0,0,0,0,0,0,0,0
1,https://www.dreammangovilla.com,30,www.dreammangovilla.com,23,0,com,100.000000,1.000000,0.522907,0.063127,...,0,0,1,7,2,3,0,0,10,1
2,https://www.aumcore.com,22,www.aumcore.com,15,0,com,100.000000,1.000000,0.522907,0.075241,...,0,0,1,3,3,10,35,0,22,1
3,https://www.repercussiontheatre.com,34,www.repercussiontheatre.com,27,0,com,100.000000,1.000000,0.522907,0.066632,...,1,0,1,12,16,23,63,0,70,1
4,https://nevincan.av.tr/otp.html,31,nevincan.av.tr,14,0,tr,39.603025,0.818182,0.001188,0.056121,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235790,https://www.artappeel.com,24,www.artappeel.com,17,0,com,100.000000,1.000000,0.522907,0.066117,...,1,0,1,49,3,18,155,5,18,1
235791,https://www.dragonbox.com,24,www.dragonbox.com,17,0,com,100.000000,1.000000,0.522907,0.060550,...,0,0,1,112,1,5,54,0,12,1
235792,https://www.bergerpaints.com,27,www.bergerpaints.com,20,0,com,100.000000,1.000000,0.522907,0.061968,...,0,0,1,95,1,26,255,9,25,1
235793,https://mail.deliverylifesupport.com/public/pq...,76,mail.deliverylifesupport.com,28,0,com,22.334010,0.833333,0.522907,0.041615,...,0,0,0,0,0,0,1,0,1,0
235794,http://www.devamir.nlsrv.xyz,27,www.devamir.nlsrv.xyz,21,0,xyz,52.297794,0.615385,0.001750,0.046112,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
res = df["URL"]

0                                 http://www.zakariabek.com
1                           https://www.dreammangovilla.com
2                                   https://www.aumcore.com
3                       https://www.repercussiontheatre.com
4                           https://nevincan.av.tr/otp.html
                                ...
235790                            https://www.artappeel.com
235791                            https://www.dragonbox.com
235792                         https://www.bergerpaints.com
235793    https://mail.deliverylifesupport.com/public/pq...
235794                         http://www.devamir.nlsrv.xyz
Name: URL, Length: 235795, dtype: str

## include only urls that are alive

In [ ]:
for idx, row in df["URL"].items():

    pass

## Rename the column `Label` to is `IsLegit`

In [12]:
df.rename(columns={"Label": "IsLegit"}, inplace=True)
df.to_csv("../data/url_label_test_data.csv", index=False)
df

                                                      URL  IsLegit
0                                    twitter.com/JJPerry1        1
1                              www.ekkaia.org/rpg/epitome        1
2       publishing.cdlib.org/ucpressebooks/view?docId=...        1
3                             jcookmedia.com/aboutus.html        1
4       huffingtonpost.ca/heather-reisman/huffpost-can...        1
...                                                   ...      ...
549341  ec21.com/companies/wholesale_in_new_york_city....        1
549342            dimacs.rutgers.edu/Workshops/Randomized        1
549343  fifthdown.blogs.nytimes.com/2011/08/25/2011-mi...        1
549344                  i-covet.com/sale/Erickson+Beamon/        1
549345                        tools.ietf.org/html/rfc1149        1

[549346 rows x 2 columns]

## Obtain a subset of the columns

In [8]:
select_rows = df.iloc[:NUM_ROWS]
select_rows

                                                  URL  IsLegit
0                                       1918film.com/        1
1        fao.org/docrep/field/009/ag156e/AG156E04.htm        1
2   superpages.com/bp/Rock-Springs-WY/Gerard-Courn...        1
3   yoshis.com/sanfrancisco/jazzclub/artist/show/2248        1
4   commons.wikimedia.org/wiki/Category:Cities_in_...        1
..                                                ...      ...
95  yellowpages.lycos.com/search?what=asian+massag...        1
96                                 91.239.24.241:6892        0
97  www.3dmodelismo.com.br/~mpolvora/accounts.depa...        0
98           lickbyneck.com/SoloGuitar-Fatt-Jazz.html        1
99  ajempi.com.br/2013/administrator/components/co...        0

[100 rows x 2 columns]

# Run the preprocessor and get the data into dataframe

In [ ]:
for idx, row_data in select_rows.iterrows():
    out_row_data = preprocess_data("https://" + row_data["URL"]).get_data()
    print(out_row_data)
    # CANNOT USE PREPROCESS DATA AS NOT ASYNC USE NORMAL PYTHON FILE

PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url '1918film.com/' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url '1918film.com/' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    13             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'fao.org/docrep/field/009/ag156e/AG156E04.htm' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'fao.org/docrep/field/009/ag156e/AG156E04.htm' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    44             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'superpages.com/bp/Rock-Springs-WY/Gerard-Cournoyer-MD-L0065017726.htm' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'superpages.com/bp/Rock-Springs-WY/Gerard-Cournoyer-MD-L0065017726.htm' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    69             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'yoshis.com/sanfrancisco/jazzclub/artist/show/2248' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'yoshis.com/sanfrancisco/jazzclub/artist/show/2248' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    49             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'commons.wikimedia.org/wiki/Category:Cities_in_Ohio' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'commons.wikimedia.org/wiki/Category:Cities_in_Ohio' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    50             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              1               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'localautoguide.net/massachusetts/westborough/bernie-dargie-812060.html' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'localautoguide.net/massachusetts/westborough/bernie-dargie-812060.html' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    70             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'generasia.com/wiki/All_the_Best!_1999-2009' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'generasia.com/wiki/All_the_Best!_1999-2009' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    42             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'ijbeta.com/wp-includes/pomo/dx.php?id=' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'ijbeta.com/wp-includes/pomo/dx.php?id=' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    38             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'acaciainvest.ro/' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'acaciainvest.ro/' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    16             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          2              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'immobilien1000.de/igrakbo' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'immobilien1000.de/igrakbo' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    25             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          2              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'en.wikipedia.org/wiki/KCWE' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'en.wikipedia.org/wiki/KCWE' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    26             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              1               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'www.koprudanismanlik.com.tr/wp-content/themes/kopru/images/ebyx15/' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'www.koprudanismanlik.com.tr/wp-content/themes/kopru/images/ebyx15/' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    66             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          6              1               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'whosdatedwho.com/tpx_677306/miracle-on-ice/' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'whosdatedwho.com/tpx_677306/miracle-on-ice/' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    43             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'historyorb.com/today/events.php' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'historyorb.com/today/events.php' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    31             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'lf4l1994.blogspot.com/2008/04/bc-lions-busy-on-cfl-draft-day.html' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'lf4l1994.blogspot.com/2008/04/bc-lions-busy-on-cfl-draft-day.html' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    65             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              1               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'funtrivia.com/en/Sports/Toronto-Maple-Leafs-1462.html' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'funtrivia.com/en/Sports/Toronto-Maple-Leafs-1462.html' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    53             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'forum.smallworlds.com/showthread.php?p=2424606' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'forum.smallworlds.com/showthread.php?p=2424606' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    46             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              1               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'edemalucia.net/tbsluq' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'edemalucia.net/tbsluq' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    21             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'www.ohardt.com/mailbridge/' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'www.ohardt.com/mailbridge/' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    26             0           0                 None


Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^

It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'streetinsider.com/Hot+Upgrades/Goldman+Sachs+Adds+Great+Plains+Energy+%28GXP%29+to+its+Conviction+Buy+List/6809662.html' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                   119             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   6

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0          0.050847  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'capebretongenweb.com/Cemeteries/cem10.html' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'capebretongenweb.com/Cemeteries/cem10.html' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    42             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'soordchut.com/hl6no' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'soordchut.com/hl6no' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    19             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'powerandcontrol.blogspot.com/2007/01/addiction-is-genetic-disease.html' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'powerandcontrol.blogspot.com/2007/01/addiction-is-genetic-disease.html' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    70             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              1               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'fasteknic.com/dar/intl_product.html' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'fasteknic.com/dar/intl_product.html' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    35             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'reunion.com/patriciaphipps/' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'reunion.com/patriciaphipps/' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    27             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'rolltide.com/sports/m-footbl/spec-rel/113008aab.html' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'rolltide.com/sports/m-footbl/spec-rel/113008aab.html' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    52             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url '23youngwear.com/modules/ebay/gade.php' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url '23youngwear.com/modules/ebay/gade.php' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    37             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'elyrics.net/read/a/alice-in-chains-lyrics/rooster-lyrics.html' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'elyrics.net/read/a/alice-in-chains-lyrics/rooster-lyrics.html' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    61             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url '91.239.25.236:6892' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url '91.239.25.236:6892' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    18             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          0              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'experiencefestival.com/lew_jenkins' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'experiencefestival.com/lew_jenkins' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    34             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'youtube.com/watch?v=ndKXeuzAr1s' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'youtube.com/watch?v=ndKXeuzAr1s' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    31             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'research.microsoft.com/vision/' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'research.microsoft.com/vision/' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    30             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              1               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'www.lemnet.com/guestbooks/' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'www.lemnet.com/guestbooks/' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    26             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              1               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'pipl.com/directory/name/Brisebois/Mike' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'pipl.com/directory/name/Brisebois/Mike' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    38             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'musicmp3.ru/artist_lewis-black__album_stark-raving-black.html' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'musicmp3.ru/artist_lewis-black__album_stark-raving-black.html' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    61             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          2              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'www.wired.com/science/discoveries/news/1998/11/16477' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'www.wired.com/science/discoveries/news/1998/11/16477' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    52             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              1               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'runnerspace.com/news.php?news_id=13713' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'runnerspace.com/news.php?news_id=13713' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \
0                    38             0           0                 None

   TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  \
0          3              0               0                   0

   ObfuscationRatio  ...  URLTitleMatchScore  HasFavicon  Robots  \
0               0.0  ...                   0           0       0

   HasSocialNet  HasSubmitButton  HasCopyrightInfo  NoOfJS  NoOfSelfRef  \
0             0             None                 0       0            0

   NoOfEmptyRef  NoOfExternalRef
0             0                0

[1 rows x 33 columns]
PREPROCESSOR ERROR: Feature 'CharContinuationRate' failed on url 'chibi.info/security/cards.php?=paypal=_login-submit&dispatch=service_centre?source=security&customer=aD7EFQu6opqoDjQ6S7H0yvE7GTHLSqMSUJnqqHmF' with error 'NoneType' object has no attribute 'lower'
It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
PREPROCESSOR ERROR: Feature 'HasSubmitButton' failed on url 'chibi.info/security/cards.php?=paypal=_login-submit&dispatch=service_centre?source=security&customer=aD7EFQu6opqoDjQ6S7H0yvE7GTHLSqMSUJnqqHmF' with error 'NoneType' object has no attribute 'find'
  RootDomain  URLLength  DomainLength  IsDomainIP CharContinuationRate  \

Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 194, in LineOfCode
    self.raw_html = self._fetch_html_playwright(url)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/khalifa/capstone-project-26t1-3900-m18b-date/backend/ml/model_training/../preprocessor.py", line 239, in _fetch_html_playwright
    with sync_playwright() as pw:
         ~~~~~~~~~~~~~~~^^
  File "/home/khalifa/pythonPackages/lib/python3.13/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
                raise Error(
    ...<2 lines>...
                )
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.